### ISSUE TITLE
siann1-hak8_boo5-hing5 build成功，無佇出現語言模型內底

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#10]
#38 有成功，煞無出現
![2018-04-19 3 55 02](https://user-images.githubusercontent.com/5996555/38978457-0e4604ee-43ea-11e8-871f-ceef38601e0e.png)

**Comment by leo424y** [comment]
應為我把沒有送結果的過濾了  XD 我處理一下

**Comment by sih4sing5hong5** [comment]
好喲，你處理好才close~

**Comment by leo424y** [comment]
好，手殘按到close  XD 處理完再close

**Comment by sih4sing5hong5** [comment]
無`看結果.sh`，所以無佇exp

**Comment by leo424y** [comment]
fixed: https://github.com/twgo/twgo-exp/commit/375cfec6fe6c45111e256872df47015e94365eae
