### ISSUE TITLE
test的docker愛用取代的

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#104]
第一逝無一定是`FROM`
請改用取代的

原本
https://github.com/twgo/DNN-test/blob/%E9%8C%84%E9%9F%B3%E8%85%B3%E6%9C%AC/Dockerfile
改做
https://github.com/twgo/DNN-test/blob/c6f38fcb803a9b17460ded2c86d10591c6969cf1/Dockerfile

**Comment by sih4sing5hong5** [comment]
https://github.com/twgo/twgo-exp/blob/d14f8210c48c610435480517efa23796528f8ca2/app/controllers/githubs_controller.rb#L15

**Comment by leo424y** [comment]
已修改並式接可行，很抱歉我實在不周道，感謝指出

**Comment by sih4sing5hong5** [comment]
多謝
