### ISSUE TITLE
github api limit

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#109]
![2018-10-08 12-08-28](https://user-images.githubusercontent.com/5996555/46592192-eeacd280-caf2-11e8-8693-12e6d5f8e96f.png)

**Comment by leo424y** [comment]
可能實驗太密集，目前可運作

**Comment by sih4sing5hong5** [comment]
程式有辦法減少api的次數嗎？

**Comment by leo424y** [comment]
目前必要才call 我找找哪個部分可縮減
