### ISSUE TITLE
ActionController::InvalidAuthenticityToken

### ISSUE THREAD

**Issue by leo424y** [twgo/twgo-exp#11]
production 更新label會噴錯，待解

**Comment by sih4sing5hong5** [comment]
好佳哉我緊共關掉 xdd

會當tdd矣

**Comment by leo424y** [comment]
local好好的說，這個是porduction的問題XD，好興奮，又有新東西可學！！

**Comment by leo424y** [comment]
TDD TDD TDD 很重要，要打三遍

**Comment by leo424y** [comment]
fixed:  Rails 設定問題 https://github.com/twgo/twgo-exp/commit/e4f9ba0153ba437fd7c67da08c063d143a5b0143
