### ISSUE TITLE
DNN接實驗無走

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#110]
![2018-10-09 14-37-53](https://user-images.githubusercontent.com/5996555/46650948-f2af2200-cbd0-11e8-83f8-a2b7f29b5830.png)

點半試，這馬試，CI攏無走

**Comment by sih4sing5hong5** [comment]
共dnn-test內底 `_開頭的branch` thai掉就會走--ah

**Comment by leo424y** [comment]
抱歉，因為前面api limit issue的不正常中斷導致_開頭沒有被砍掉
