### ISSUE TITLE
dnn-test的branch傷濟，有的我選袂著

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#116]

**Comment by sih4sing5hong5** [comment]
服務sí--looh
502 bad gateway

Yang-Hsiang Chang <notifications@github.com> 於 2018年10月13日週六 下午12:26 寫道：

**Comment by leo424y** [comment]
老大抱歉，調了新的更新完忘了 up ，已啟動

**Comment by leo424y** [comment]
![screen shot 2018-10-15 at 10 45 07 am](https://user-images.githubusercontent.com/1384394/46927350-70f34480-d067-11e8-931c-61fe56a615ab.png)
已解決，原來api有30筆這個這限制，已開到200

**Comment by sih4sing5hong5** [comment]
感謝～～

所以是github的設定？抑是gem的設定？

**Comment by leo424y** [comment]
https://github.com/octokit/octokit.rb#default-results-per_page  github default 30,  gem 可改
