### ISSUE TITLE
DNN-test的github一直出現`_thaumaiku+lm-decoding` branch

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#119]
我進前試過，只有github內有`_開頭`的branch
jenkins就袂走

毋過` _thaumaiku+lm-decoding`一直出現，我thai 5擺猶原閣會出現
這馬無法度做實驗
https://github.com/twgo/DNN-test/branches

**Comment by leo424y** [comment]
thaumaiku+lm-decoding 不存在了，但在排內沒同步，
我手動把這個問題branch 實驗 砍了，請再試。 
並試著把砍 branch 的時間縮短

有勞老大再試，謝謝

**Comment by sih4sing5hong5** [comment]
> thaumaiku+lm-decoding 不存在了

毋知為啥物無去--ah
我重push
