### ISSUE TITLE
DNN接實驗的branch敢e-tang排先後

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#121]
branch排就好
train就照原本新的排頭前按呢，莫改

**Comment by leo424y** [comment]
啊，歹勢，是我沒進入狀況！謝謝老大包涵

**Comment by leo424y** [comment]
可是這個的 sorting 是github預設說，我找找有沒有api setting

**Comment by leo424y** [comment]
sorry我看錯 要train新的排前，我改改

**Comment by leo424y** [comment]
![screen shot 2018-10-17 at 3 20 26 pm](https://user-images.githubusercontent.com/1384394/47070198-5e256f00-d223-11e8-92e9-663f0cd0251a.png)

發現之前沒sorting ，Done!

**Comment by leo424y** [comment]
![screen shot 2018-10-17 at 3 43 01 pm](https://user-images.githubusercontent.com/1384394/47070265-71383f00-d223-11e8-93e8-a0e74e280238.png)
這個圖才對

**Comment by sih4sing5hong5** [comment]
Loo-lat
