### ISSUE TITLE
新核心的處理dockerfile

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#128]
Tshan像 #127 按呢的dockerfile
你khng佇to一个github repo？

**Comment by leo424y** [comment]
本來想說只有砍檔不用開

但現在開囉，謝謝老大提出問題！
https://github.com/twgo/finalfile/blob/master/Dockerfile

**Comment by sih4sing5hong5** [comment]
有檔案就愛放出來
以後交接較袂舞著ka-ti
