### ISSUE TITLE
jenkins的信標題，加顯示branch

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#13]

**Comment by leo424y** [comment]
多虧jenkins神強的社群

git plugin 給了個全域變數 $GIT_BRANCH

已套用！


寄給我自己的測試信
![screen shot 2018-05-09 at 1 11 46 pm](https://user-images.githubusercontent.com/1384394/39796680-91ae6b82-538a-11e8-9fb5-34242fadc67c.png)

**Comment by sih4sing5hong5** [comment]
讚喲
