### ISSUE TITLE
接的實驗攏無走

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#132]
Tsang接的，到tann猶原無出現，佮 #130 敢有關係？

**Comment by leo424y** [comment]
目前初估是全部刷新造成工作死掉，改刷最後十個。目前 都順利完成工作 沒死掉 https://exp.iis.sinica.edu.tw/s/busy

fix by
 https://github.com/twgo/twgo-exp/commit/f6835cfc794d98b8ebfe49ddce4eaebaa83a5b34

**Comment by leo424y** [comment]
再次查看，雖然實驗都有跑，發現還有會死掉的 worker 我再追。後續有實驗再請老大直接貼給我做

**Comment by leo424y** [comment]
![screen shot 2018-11-01 at 1 46 30 pm](https://user-images.githubusercontent.com/1384394/47834952-a83e5100-dddc-11e8-8e58-a3b8b87b46ad.png)
DNN-train：24 接10個已完成

**Comment by leo424y** [comment]
抱歉，還沒接完，目前實驗中。
錄音腳本
錄音腳本+lm-decoding

**Comment by sih4sing5hong5** [comment]
勞力～
