### ISSUE TITLE
DNN-train：25 接

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#133]
25閣tih build，若build好幫我接

16k攏是固定這10个branch
```

  2017陳60句
  2017陳60句+lm-decoding
  thaumaiku
  thaumaiku+lm-decoding
  tw01test-當作1000語者
 tw01test-當作1000語者+lm-decoding
  twisas-test
  twisas-test+lm-decoding
  錄音腳本
  錄音腳本+lm-decoding
```

**Comment by sih4sing5hong5** [comment]
到301就無走--looh


|訓練資料↓ | testing→ |  tw01test-1000 | twisas| 錄音腳本 | 陳60 | 頭戴式|
| ------| -------- | -------- | ------ | ------ | -------- |--- |
| tw0102+twisas(203) |TDNNF| 22.16(288)|46.44(289)|50.13(293)| 47.51(284)|35.29(286)|
| tw0102+twisas(203) |TDNNF LMWER| 71.14(291)|61.13(290)|61.88(292)|58.27(285)|41.81(287)|
| tw0102+twisas(203) |TDNNF LMSER| 12.46(291)|26.72(290)|36.08(292)|18.66(285)|12.94(287)|
| tw0102+twisas本(204) |TDNNF| 20.88(299)|48.08(301)|-|46.27(294)|35.00(297)|
| tw0102+twisas本(204) |TDNNF LMWER| 71.18(300)|-|-|47.12(296)|42.67(298)|
| tw0102+twisas本(204) |TDNNF LMSER| 12.53(300)|-|-|16.17(296)|10.59(298)|

**Comment by sih4sing5hong5** [comment]
> 手癢重構有問題，已恢復接著跑，明早應可能跑完

TDD～

**Comment by sih4sing5hong5** [comment]
Lóo-la̍t ～

**Comment by leo424y** [comment]
沒TDD重構真得是自找的 TDD TDD ！正在多看人家如何寫
