### ISSUE TITLE
11/05 阿翔工課

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#141]
> 調查局安裝後續追蹤 
> 辨識實驗

這2項你按算按怎做？

**Comment by leo424y** [comment]
1. 陳先生有系統問題會找我，我持續幫他解決
2. 在想要不要做批次建實驗的功能，省得一次還要挑十幾個，避免嚴重重工

**Comment by sih4sing5hong5** [comment]
> * 陳先生有系統問題會找我，我持續幫他解決

若有問題，就發issue，才close

> * 在想要不要做批次建實驗的功能，省得一次還要挑十幾個，避免嚴重重工

我是感覺需要，毋過tsit-ma莫做，因為你系統閣愛試

若你無別項khang-khue，敢會使幫我鬥做一寡？

**Comment by leo424y** [comment]
好，有問題我發 issue ，隊長有事需要做我先辦

**Comment by sih4sing5hong5** [comment]
#142
