### ISSUE TITLE
整理asr資料做kaldi format

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#142]
1. 照`ASRtrains.txt`整理kaldi format
2. 照`ASRtrains.txt`掠asr面頂的音檔:http://asr-offline.iis.sinica.edu.tw/辨識

台語整理做1个kaldi format(text, segment, wav.scp ...)，用臺羅
華語嘛整理做1个
`ASRtrains.txt`我用email寄予你，你做了予逐家

**Comment by leo424y** [comment]
收到，著手進行中

**Comment by leo424y** [comment]
![screen shot 2018-11-05 at 10 39 54 am](https://user-images.githubusercontent.com/1384394/47975040-32412f00-e0e7-11e8-8322-2671e30874d3.png)
往下只能拉到 7737 第一筆之6519無法抓取

**Comment by leo424y** [comment]
見 https://github.com/twgo/asrtrans

**Comment by leo424y** [comment]
丞宏

阿翔整理asr資料做kaldi format #142 報告
此為丞宏之issue，列在 https://github.com/twgo/twgo-exp/issues/142
若阿翔有不周之處，還請指出

轉出kaldi結果分別分為三資料夾/音檔序號
tai
tong
hua

音檔與原始需求文件請於附件下載

(以下為private，需為專案成員方可瀏覽，亦可於附件result.zip取得轉出結果)
華語5664例
https://github.com/twgo/asrtrans/blob/master/hua/5664/segments

台羅6519例
https://github.com/twgo/asrtrans/blob/master/tai/6519/segments

通用6519例
https://github.com/twgo/asrtrans/blob/master/tong/6519/segments

註：wav.scp原始路徑設例為/usr/local/kaldi/egs/formosa/s5/tshi3/train_free/Kaldi辨識_5664.wav，可適時取代
