### ISSUE TITLE
DNN-train 需要重走

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#151]
https://jenkins.iis.sinica.edu.tw/job/DNN-train/42/console

https://jenkins.iis.sinica.edu.tw/job/DNN-train/43/console
```

URL: https://exp.iis.sinica.edu.tw/rounds/refresh
Sending request to url: https://exp.iis.sinica.edu.tw/rounds/refresh
Response Code: HTTP/1.1 502 Bad Gateway
```

**Comment by leo424y** [comment]
exp 修復中，已先將 jenkins DNN-train 
refresh 拿掉，實驗執行中

**Comment by leo424y** [comment]
https://jenkins.iis.sinica.edu.tw/job/DNN-train/44/
https://jenkins.iis.sinica.edu.tw/job/DNN-train/45/

接來會接實驗
https://github.com/twgo/twgo-exp/issues/152
