### ISSUE TITLE
asr 核心會方便抽換嗎？

### ISSUE THREAD

**Issue by leo424y** [twgo/twgo-exp#156]
http://asr.iis.sinica.edu.tw
老大，高老師在問 asr 的核心會方便抽換嗎？
若作業上會太麻煩的話就不打擾你囉
 @sih4sing5hong5

**Comment by leo424y** [comment]
另一個相關問題

少剛：線頂辨識的source code可以提供嗎？

感謝老大播冗回應

**Comment by sih4sing5hong5** [comment]
> http://asr.iis.sinica.edu.tw
> 老大，高老師在問 asr 的核心會方便抽換嗎？
> 若作業上會太麻煩的話就不打擾你囉
> @sih4sing5hong5

超麻煩，用docker較好

**Comment by sih4sing5hong5** [comment]
> 另一個相關問題
> 
> 少剛：線頂辨識的source code可以提供嗎？

前端：
```
gu2-im1_pian7-sik4_offline
gu2-im1_pian7-sik4 
```
後端：
https://github.com/i3thuan5/hok8-bu7/blob/master/%E4%BD%BF%E7%94%A8%E7%AF%84%E4%BE%8B/Kaldi%E6%9C%8D%E5%8B%99/docker-compose.yml
其中伊可能有興趣的所在：  https://github.com/i3thuan5/tai5-uan5_gian5-gi2_hok8-bu7/blob/master/%E8%87%BA%E7%81%A3%E8%A8%80%E8%AA%9E%E6%9C%8D%E5%8B%99/Kaldi%E4%BB%8B%E9%9D%A2.py#L77-L88

**Comment by leo424y** [comment]
收到，那若要改成抽換版還是以docker形式寫！
今年學超多的，docker這個角色太重要啦！
感謝老大，我就把資訊轉給提問伙伴
