### ISSUE TITLE
予鴻欣語料

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#16]
等 #15 

整理`docker cp`指令
https://stackoverflow.com/a/22050116

1. 原始語料
「twisas+tw01+tw02」branch內底的「/usr/local/pian7sik4_gi2liau7」

2. 去除無合理音標的tw01+tw02，而且加上20180207版本的twisas，做成「臺羅的kaldi格式」
「twisas+tw01+tw02」branch內底的「/usr/local/kaldi/egs/taiwanese/s5c/data/train」
臺羅版本的lexicon過一陣仔才會處理好，到時才予你

3. 通用的tw01+tw02，佮轉做通用的20171110版本twisas，攏是「通用的kaldi格式」
ricer原始的語料是kaldi格式的通用語料

tw01+tw02的kaldi格式的通用語料佇「tw01+tw02_thong」branch內底的「/usr/local/kaldi/egs/taiwanese/s5c/data/train」
20171110版本twisas的通用版本佇Dropbox的「資料分享/20171110twisas」

**Comment by leo424y** [comment]
已先整理到一個資料夾讓他scp，docker尚需設定才能對外，稍後處理。

**Comment by leo424y** [comment]
已給語料，先close
