### ISSUE TITLE
EXP定時主動撈CI  需與 Jenkins 同步

### ISSUE THREAD

**Issue by leo424y** [twgo/twgo-exp#17]
- [x] 進首頁檢查同步狀態
- [ ] 改jenkins trigger設定

**Comment by sih4sing5hong5** [comment]
有`building`佮`queue`

**Comment by leo424y** [comment]
突然發現可能要先把jenkins論詢github改成commit trigger jenkins不然五分鐘內多次commit就會漏實驗

**Comment by sih4sing5hong5** [comment]
人工揤`commit and run`，應該愛記commit hash，毋是記commit branch
就袂有這種問題

**Comment by sih4sing5hong5** [comment]
https://github.com/twgo/siann1-hak8_boo5-hing5/issues/18
