### ISSUE TITLE
套件過時

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#18]
這應該有研究/解決的價值

![2018-04-30 08-33-23](https://user-images.githubusercontent.com/5996555/39412570-35c67a0c-4c51-11e8-987c-b4be086f99c3.png)

**Comment by leo424y** [comment]
fixed! Thanks to your suggestion https://github.com/twgo/tw-on-youtube/commit/3aa0223186b98726b94f5f8dae1676a2efc7ee26
