### ISSUE TITLE
實驗連結改用domain name

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#19]
![2018-04-30 08-36-20](https://user-images.githubusercontent.com/5996555/39412599-9a7700e8-4c51-11e8-9e68-93900890373f.png)

**Comment by leo424y** [comment]
已替換，感謝指出 https://github.com/twgo/twgo-exp/pull/6/commits/ca5e500269744fc0faff636ed405e90a1e1fd56d

**Comment by sih4sing5hong5** [comment]
好矣就直接close無要緊
