### ISSUE TITLE
實驗整合系統建置討論

### ISSUE THREAD

**Issue by leo424y** [twgo/twgo-exp#2]
對於整合系統 EXP 有任何看法或需求請在此討論

# EXP CI show Rounds
- [ ] CI 結果整合爬取
  - [x] 識別資訊傳遞 jenkins id,  commit id, commit tag...
  - [x] 可以加label註記
  - [x] 可連結dockerfile
  - [x] deploy
  - [ ] 撈sample

- [x] 資料展示
  - [x]  全部實驗結果表列，可sort , filter
  - [x] 只需要能接上游，不必show code
  - [x] gi commit 列出上游資訊
  - [x] gentelella 收放元件，圖表展示 https://colorlib.com/polygon/gentelella/#
  - [x] 辨識率變化圖 (錯誤率/時間)  
  - [x] 可展示
  - [x] 可分支展示

# EXP CI control
- [x] 實驗串接
  - [x] 顯示, tested
  - [x] 指定開啟, tested
  - [x] 編輯
  - [x] 聲學後跑 outside
- [x] Knowhow
  - [x] gem github show
  - [x] update
  - [x] create branch

# Model 
- Round 實驗集(一個完整的辨識引擎)
  - jenkins id  :integer
  - commit id  :string
  - docker id
  - rate  
  - info  kaldi ver, pip3 freeze

# Data 展示思考
- [x] 實驗下的參數存在 https://github.com/twgo/twgo-exp/issues/2#issuecomment-370996613
- [x] log text不用存db https://github.com/twgo/twgo-exp/issues/2#issuecomment-370996778

# Wireframe
![a1_2](https://user-images.githubusercontent.com/1384394/37449343-da9b1684-2864-11e8-942a-90d25ff78fa8.png)

# UI 
https://github.com/twgo/twgo-exp/issues/2#issuecomment-369533222

**Comment by leo424y** [comment]
要快速建管理系統的話 有 activeadmin 這套 gem 可用
http://demo.activeadmin.info/admin
可以依需求再來調整內容

**Comment by leo424y** [comment]
兩個疑問 
- [ ] 實驗下的參數存在哪？是不是要一併log實驗材好重做
- [ ] log text 必要嗎？上萬筆若對後續無助，應不寫入db，或備份text即可

**Comment by sih4sing5hong5** [comment]
## 參數
https://github.com/sih4sing5hong5/kaldi/blob/taiwanese/egs/taiwanese/s5c/%E8%B5%B0%E8%A8%93%E7%B7%B4.sh#L21-L22

其他參數都不是數字型式

**Comment by sih4sing5hong5** [comment]
```
log text 必要嗎？上萬筆若對後續無助，應不寫入db，或備份text即可
```
可以查就好，不用db

**Comment by leo424y** [comment]
OK不db

有不是數字的話，所以我要備份參數是把整個 走訓練.sh copy，還是如何才能完整

**Comment by sih4sing5hong5** [comment]
實驗數據較需要「無仝的dockerfile之間，紀錄看結果內底彼4,5个的比較」，才會當看調整好bai
「仝一个dockerfile的內部結果」愛用的時機是「辨識率bai的時陣，愛查原因」

**Comment by sih4sing5hong5** [comment]
```
有不是數字的話，所以我要備份參數是把整個 走訓練.sh copy，還是如何才能完整
```
記kaldi彼个的commit hash較好

**Comment by leo424y** [comment]
請問
`kaldi彼个的commit hash`
如何取得

**Comment by sih4sing5hong5** [comment]
https://stackoverflow.com/a/949391/3640653
git rev-parse HEAD
git log

**Comment by sih4sing5hong5** [comment]
閣有存pip3 freeze的相依性

**Comment by leo424y** [comment]
還是只需記錄dockerfile即可，一定能重現
```
實驗數據較需要「無仝的dockerfile之間，紀錄看結果內底彼4,5个的比較」，才會當看調整好bai
「仝一个dockerfile的內部結果」愛用的時機是「辨識率bai的時陣，愛查原因」
```
每個實驗都以dockerfile來管理，把每個(有大變動)實驗都開一個branch，只需要以branch當作key，記在實驗系統

**Comment by sih4sing5hong5** [comment]
```
還是只需記錄dockerfile即可，一定能重現
```
無法度，因為我會改kaldi佮python的script
所以逐擺clone的結果無相仝
著一定愛記錄docker版本, git版本, python package版本

**Comment by sih4sing5hong5** [comment]
```
每個實驗都以dockerfile來管理，把每個(有大變動)實驗都開一個branch，只需要以branch當作key，記在實驗系統
```
kaldi的實驗組合有較濟
方法1+語料A
方法1+語料B
方法1+語料AB
方法2+語料A
...

這用branch可能誠歹管理？

我是感覺，逐个commit攏做ci，攏記錄，只是咱會當針對各別的commit加tag
咱才filter tag來比較實驗結果
抑是有啥物方法，按呢較好管理

**Comment by leo424y** [comment]
```
逐个commit攏做ci，攏記錄，只是咱會當針對各別的commit加tag
咱才filter tag來比較實驗結果
```
這應該是最完整的方式，我贊成

jenkins api已會把該commit id 傳出，也應有tag套件可用

**Comment by leo424y** [comment]
<img width="411" alt="screen shot 2018-03-13 at 10 25 09 am" src="https://user-images.githubusercontent.com/1384394/37319175-ffab2c1a-26a8-11e8-8cc9-55e153707462.png">
<img width="410" alt="screen shot 2018-03-13 at 10 25 20 am" src="https://user-images.githubusercontent.com/1384394/37319176-ffdc7720-26a8-11e8-98fc-26cad8a0abda.png">

@sih4sing5hong5 
請教與確認一下，你有建議或我有誤都請指出，謝謝

- 你上週給的是聲學ci跑完要進twgo-exp的結果
- 將使用git commit_id 與commit_tag幫助區別成效
- 每次實驗取一個最佳(錯誤率最低)作代表(可以製成趨勢圖)
- 使用SER作代表

以下你給的資料有沒有不需進twgo-exp的？
- log 及其內全部
  - analyze_alignments 只有1個
  - acoustic_rescore
  - decode
  - fmllr_pass1，fmllr_pass2 數量是變動的嗎？(more, or less?)
- num_jobs 只有一個數字，需要嗎？
- trans.1 ... 打開有亂碼，需要嗎？
- wer_5_0.0...
- scoring 及其內全部
 - text.filt 是正解
 - txt
 - tra
 - best_path

**Comment by sih4sing5hong5** [comment]
```
將使用git commit_id 與commit_tag幫助區別成效
```
閣會當佇管理系統加tag，親像github的label

```
log 及其內全部 
```
log攏存，規个資料夾存就好，動態掠
```
使用SER作代表
```
佇檔案內是WER，才是愛的
```
num_jobs 只有一個數字，需要嗎？
trans.1 ... 打開有亂碼，需要嗎？
```
這兩个免存
```
scoring 及其內全部 
```
tra免
log/best_path就存

**Comment by leo424y** [comment]
已依實驗結果資料夾擬wireframe如下，將進行UI製作，若有問題建議還請指出 @sih4sing5hong5 
![a1](https://user-images.githubusercontent.com/1384394/37378032-75a41bc4-2768-11e8-843f-ae8235b39d18.png)
![a2](https://user-images.githubusercontent.com/1384394/37378033-75dfc3c2-2768-11e8-998d-e18d83055f90.png)
![a3](https://user-images.githubusercontent.com/1384394/37378035-7619a3bc-2768-11e8-9b18-b143ae598f5f.png)
![b1](https://user-images.githubusercontent.com/1384394/37378036-765e53f4-2768-11e8-9eba-d317cd749006.png)
![c1](https://user-images.githubusercontent.com/1384394/37378037-7699e52c-2768-11e8-88fa-0e037245ca73.png)

**Comment by sih4sing5hong5** [comment]
@leo424y 讚喲
我感覺先做有趨勢圖彼个就好
`show詳情`揤落就共規包的log攏掠落來就好

**Comment by leo424y** [comment]
OK先做有趨勢圖的，詳情就整包下載，label註記也就提升到這裡，點選可編，搜尋可得。
![a1_2](https://user-images.githubusercontent.com/1384394/37380004-794b4ea6-2771-11e8-99b8-3a85bcfc3d20.png)

**Comment by leo424y** [comment]
@sih4sing5hong5 
我在twisas+tw01+tw02 聲學/語言，依你給的實驗結果數據folder  `decode_train_dev` 找到分佈在tri1, tri2, tri3, tri4 底下，且tri4有 decode_train_dev.si 

有以下問題

- 1次實驗即是備份 tri1, tri2, tri3, tri4, 底下的decode_train_dev嗎？
- tri1, tri2, tri3, tri4 會變動嗎？tri5...
- tri4有 decode_train_dev.si 也是要的嗎？
- 看你傳給我壓縮檔使用 .tar.gz 是推薦的格式嗎？
- 聲學實驗、語言實驗，兩個要備份的內容都一樣嗎(decode_train_dev)？


新發現
```
# 這個指令可以壓全部有decode_train_dev含decode_train_dev.si
tar -zcvf all_decode_train_dev.tar.gz `find . -print | grep -i 'decode_train_dev'`  
```

**Comment by sih4sing5hong5** [comment]
若是咱決定用docker image，敢閣有需要另外備份？

---

    1次實驗即是備份 tri1, tri2, tri3, tri4, 底下的decode_train_dev嗎？
著

    tri1, tri2, tri3, tri4 會變動嗎？tri5... 不過我用find 找 decode_train_dev其實沒差

好，用find

    tri4有 decode_train_dev.si 也是要的嗎？

好

    看你傳給我壓縮檔使用 .tar.gz 是推薦的格式嗎？

是無差偌濟，毋過這較方便

    聲學實驗、語言實驗，兩個要備份的內容都一樣嗎(decode_train_dev)？

著

**Comment by leo424y** [comment]
> 若是咱決定用docker image，敢閣有需要另外備份？

一針見血！有image就不必另外備份了。

這才查了一下一次decode_train_dev下的資料有800多mb！

若我們已完整保留image，那需要的時後再打開來把 decode_train_dev 爬出來似乎比較經濟，

- 那麼我先存 image id 以利回頭撈結果

**Comment by sih4sing5hong5** [comment]
存image id敢有安全？敢無可能hong9系統thai5掉？
抑是用tag強制保留較好？

**Comment by leo424y** [comment]
目前整個CI docker流程沒有delete 的動作，若誤刪仍可由dockerfile重跑實驗恢復，我亦將常用image(相對語言較久才跑一次的聲學) push到docker hub 這樣異地備份，應不致於造成危險？

**Comment by sih4sing5hong5** [comment]
我其實無了解，因為我捌佇docker build看著`delete middle image XXXX`這種資訊
毋知影佮這有關係無？

**Comment by leo424y** [comment]
你說的像是`build --rm 能刪掉intermediate containers `
中間container 非我們存的 結果image
https://docs.docker.com/edge/engine/reference/commandline/build/

目前Jenkins plugin 是可以安全存下來的，且無人為操作之必要，於plugin設定很明確，一build完就push。

**Comment by leo424y** [comment]
@sih4sing5hong5   我要準備寫用EXP改Github  Dockerfile 功能，這是一個最直覺能連動實驗的方式

問題：

- 我目前設計就讓siann1-hak8_boo5-hing5跑完後，接著讓gi2-gian5_boo5-hing5所有branch全部都跑一次？

- 目前會跑CI的Dockerfile實驗有 聲學模型、語言模型(改叫outside tesg)，另外，你說GPU版的聲學模型程式不一樣，照理應該再開一個REPO來版控？ 這樣CI也才好呼叫。

- 之後需加功能成可控制要接的Dockerfile? ex 聲學，接聲學GPU，接語言(outside test)

方法會是命EXP用CI最新的build號去改 Dockerfile From  image 版本號，CI就會自動排程跑

**Comment by sih4sing5hong5** [comment]
>    我目前設計就讓siann1-hak8_boo5-hing5跑完後，接著讓gi2-gian5_boo5-hing5所有branch全部都跑一次？
應該是需要按呢，毋過這若會開傷濟時間，這項就較晏才來做

>    目前會跑CI的Dockerfile實驗有 聲學模型、語言模型(改叫outside tesg)，另外，你說GPU版的聲學模型程式不一樣，照理應該再開一個REPO來版控？ 這樣CI也才好呼叫。
好，到時等系統攏好矣，才來做這，我這馬嘛無時間做GPU的工課

>    之後需加功能成可控制要接的Dockerfile? ex 聲學，接聲學GPU，接語言(outside test)
意思是`用一个dockerfile`，控制`siann1-hak8_boo5-hing5跑完後，接著讓gi2-gian5_boo5-hing5所有branch全部都跑一次`佮`GPU版的聲學模型`？
這好管理較重要，若是你有需要，才閣來寫

這馬較趕緊的是
- [x] 聲學自動做
- [x] 聲學結果自動顯示佇網頁
- [ ] 語言outside testing會當指定佮指定的聲學做訓練
- [ ] outside testing結果自動顯示佇網頁

頭前兩項攏好矣嘛？
第三四項就盡量先做

**Comment by leo424y** [comment]
一二四都OK了，但目前是要手按同步，會再來加自動同步。三只差讓要做的語言自動去改要接的聲學image，正在看用API改dockerfile，我會加快腳步。

**Comment by sih4sing5hong5** [comment]
https://github.com/twgo/twgo-ci/issues/6
