### ISSUE TITLE
接實驗揤落，jenkins無反應

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#21]
聲學模型 #52 做好了後
欲做別的語言模型實驗

毋過揤接實驗，語言模型 煞無振動

![default](https://user-images.githubusercontent.com/5996555/39734760-2cda58f4-52ab-11e8-80b0-b4c751e5e82f.png)

**Comment by leo424y** [comment]
下完實驗後會commit要接的image去該branch
目前要等五分鐘會去github撈一次
剛去看有個六小時前的實驗應該有在跑
