### ISSUE TITLE
docker run的指令囥佇佗位

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#24]
#8 原本 docker run + ssh 的指令

**Comment by leo424y** [comment]
有顯示光碟的成功build才能看喔： port在5000
例：進CI後
docker run -it localhost:5000/siann1-hak8_boo5-hing5:52 /bin/bash
![screen shot 2018-05-08 at 5 18 03 pm](https://user-images.githubusercontent.com/1384394/39748894-e956ad24-52e3-11e8-9073-9bbc0ecc391f.png)

**Comment by sih4sing5hong5** [comment]
走失敗的，敢會使傳上尾一个的`docker image hash`
親像 [聲學51](https://jenkins.iis.sinica.edu.tw/job/siann1-hak8_boo5-hing5/51/console)
回傳上尾一步`1e1657f10077`
```
Step 48/53 : RUN git pull
 ---> Using cache
 ---> 1e1657f10077

Step 49/53 : RUN bash -c 'time bash -x 走訓練.sh  2>&1'
Fail...
```

**Comment by leo424y** [comment]
1e1657f10077 是 48 的cache
無法直接使用

不成功的build沒法push image
故目前尚法取得失敗實驗image

但或許可以讓你想進入的環境先有成功的build
也就是註解掉失敗的step

即能進入image

**Comment by sih4sing5hong5** [comment]
若有需要我才入去看hash好矣 XD
先莫做這
