### ISSUE TITLE
閣咧走會顯示「無印結果」

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#25]
![2018-05-08 16-24-16](https://user-images.githubusercontent.com/5996555/39746233-50930f76-52dc-11e8-97a2-c26cb447f89a.png)

**Comment by leo424y** [comment]
沒結果的改顯示 N/A 包含執行中，執行完若有結果會更新。https://github.com/twgo/twgo-exp/pull/6/commits/6716ae143f3ca37d83b85cc22bb6e96e5573519a

**Comment by sih4sing5hong5** [comment]
若是真實`無印結果`，會按怎顯示？看起來嘛是`N/A`
