### ISSUE TITLE
仝一个commit build兩擺

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#27]
![2018-05-09 07-20-40](https://user-images.githubusercontent.com/5996555/39787755-7eb72838-5359-11e8-8688-fca96dfeec3b.png)

**Comment by leo424y** [comment]
#5​6 May 8, 2018 9:45 PM
--
#5​5 May 8, 2018 7:47 PM



有點jenkins到重跑嗎？不然目前是檢查有新的commit才會跑

之後改成git hook 啟動應會更穩定，有commit就跑
