### ISSUE TITLE
docker傳參數

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#29]
https://peihsinsu.gitbooks.io/docker-note-book/content/dockerfile-env-vs-arg.html

**Comment by sih4sing5hong5** [comment]
exp用commit，實在是無啥好，會汙染著原本的程式，應該愛改做args
![2018-05-24 17-52-27](https://user-images.githubusercontent.com/5996555/40478311-463330aa-5f7b-11e8-824e-67df3fc690b8.png)

**Comment by leo424y** [comment]
收到，我來翻翻Jenkins plugin

**Comment by leo424y** [comment]
仔細查了一下，有相關plugin可做進階設定，但其設定稍繁索，且在我們目前「commit and run」的架構下，建議就另開一個接實驗用的repo，即不汙染原始repo ，適用目前  gi2-gian5_boo5-hing5   ( 聲學模型測試) ，而未來有上游的repo也可如此。
作法：
- 1. 另開一repo 命名「to_siann1-hak8_boo5-hing5_tshik4-tshi3 」，或有其它建議？
- 2. 接實驗時，新的commit會從原gi2-gian5_boo5-hing5   ( 聲學模型測試)，撈dockerfile出來在1. repo commit
- exp即改撈取1. 之結果
- 3. 接實驗統一於接實驗分頁進行，它處單純提供實驗數據。 

如此，可用較小成本，追求乾靜的實驗用dockerfile

請隊長評估，謝謝

**Comment by leo424y** [comment]
@sih4sing5hong5  請隊長評估「另開接實驗專用repo」之提案，有勞了。

**Comment by sih4sing5hong5** [comment]
> 有相關plugin可做進階設定

連結～～

佇jenkins處理是較好，我愛想一下流程

**Comment by leo424y** [comment]
https://wiki.jenkins.io/display/JENKINS/CloudBees+Docker+Custom+Build+Environment+Plugin

**Comment by leo424y** [comment]
Jenkins.iis 已安裝 在建置環境   Build inside a Docker container 可設定，只是開新repo 控制我較有把握實現

**Comment by leo424y** [comment]
Jenkins原生控制docker 參考 https://jenkins.io/doc/book/pipeline/docker/

**Comment by sih4sing5hong5** [comment]
我有閒看覓咧

**Comment by leo424y** [comment]
exp commit  後 kill   jenkins_原來branch#timestamp

**Comment by sih4sing5hong5** [comment]
#54
