### ISSUE TITLE
實驗集的 `gi2-gian5_boo5-hing5`標題改做`outside test` 

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#35]

**Comment by leo424y** [comment]
5/10 meeting 上有新的命名結構，再請提供

**Comment by sih4sing5hong5** [comment]
這標題的replace，敢會使寫佇一个json抑是yaml，照這个檔案來改顯示名

**Comment by leo424y** [comment]
應該有此解，我查一下，但目前看來最多五個tag，hard cord或許也是個方法。

建議舊的repo不要改名，顯示名稱目前就照討論的走囉

siann-hak boo-hing >> 聲學模型訓練
gi-gian5.. >> 聲學模型測試
