### ISSUE TITLE
補rate的試驗

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#37]
https://github.com/twgo/twgo-exp/commit/361d6b98d04db24836e05a15e0cd89122d1df672#commitcomment-28960292

**Comment by leo424y** [comment]
https://github.com/twgo/twgo-exp/commit/c8d2ba6653471db313f1d5ef4e0e98fa9492b48c
讀了您的建議後把各rate的代號抽出來，似乎變明確了！有點像是我在讀高手寫的gem的spec XD 雖然還有距離，但實在感謝丞宏建議修改！

由於rate的顯示是將ci已爬完寫在db的資料轉換的helper
故另寫
爬得rate的寫入spec於 https://github.com/twgo/twgo-exp/commit/7562651fc28692bfb16fa3cec555b874e74bd538

但寫完覺的應該要先寫測試的，事後補怪怪，以後加新資料功能要先寫

**Comment by sih4sing5hong5** [comment]
會當用branch無，按呢會較清楚，branch你就直接merge無要緊

       expect(@worker.exp_rate).to eq @round_success_rate 
       expect(helper.show_rate_status(@round_success.rate)).to eq 123.0
按呢分開寫是單元試驗的寫法
因為你的實作攏是if-else，較有機會改害去
https://github.com/twgo/twgo-exp/blob/master/app/workers/jenkins_worker.rb#L112-L121
https://github.com/twgo/twgo-exp/blob/361d6b98d04db24836e05a15e0cd89122d1df672/app/helpers/application_helper.rb#L11-L22
所以建議閣加一个整合試驗
直接試
       expect(helper.show_rate_status(@worker.exp_rate)).to eq 123.0
無就是`莫用0、999佮888帶表狀態，直接用string抑是boolean代表狀態`，程式會較好維護
