### ISSUE TITLE
會當手動共無愛的branch藏起來

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#38]
有的branch可能是試驗用的
這馬用袂著，用設定檔來藏

1. 用一个yaml抑是json來設定
2. 用一个後臺來選

看佗一个你較方便

**Comment by leo424y** [comment]
要藏的branch統整在：https://github.com/twgo/twgo-exp/blob/49a52e6dc0263747d328f115c848bcd63cacf368/config/application.rb 也可以直接加
