### ISSUE TITLE
`語言模型`改做`outside test`

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#4]
抑是有別的較好名？

**Comment by leo424y** [comment]
因我對聲學和語言模型的任務不大清楚，故依你的決定，主要是我們做實驗是能區別，報告時大家有共識即可

**Comment by sih4sing5hong5** [comment]
好，若有想著較好的名才閣改

**Comment by leo424y** [comment]
https://github.com/twgo/twgo-exp/pull/6 
EXP系統已以repo名稱各實驗，如 ：gi2-gian5_boo5-hing5 ， siann1-hak8_boo5-hing5

報告時 `語言模型`我就改稱做`outside test`
