### ISSUE TITLE
build 61無出現佇實驗系統

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#41]
應該build過22分鐘矣
攏猶未出現

**Comment by leo424y** [comment]
已解，問題在2天前我為了加測get rate改了jenkins 的 ip 成 domain ，但 我用的 gem 不適用以 doamin連，故已改回，並將以 stub 方式測試即 #37 

案發現場 https://github.com/twgo/twgo-exp/commit/27a61b9d556908c3b15085e2dd2e26a5981876c1#diff-6a99a822ae8462d6261ca69424d77fee
