### ISSUE TITLE
接實驗無振動

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#42]
我試`free-syllable-tw01test-仝語者接上游實驗siann1-hak8_boo5-hing5/61 - tw01+tw02 - 違法的通用攏先處理做SPN - `
jenkins無反應

試第二擺
出現`下游實驗free-syllable-tw01test-仝語者已接過`

**Comment by leo424y** [comment]
https://github.com/twgo/twgo-exp/commit/04905e16fae2d7231d945dabbd31e095797ef783
已修，發現是前端form錯位了，我再查查如何測，


ps.
昨晚睡前看到爬蟲配 selenium 好酷！

`from selenium import webdriver`

https://github.com/Chalarangelo/unscrape/blob/master/unscrape.py


ps. erb 真得有夠難讀，還是react威猛，拜。

**Comment by sih4sing5hong5** [comment]
整合試驗： selenium
後端：做假的資料庫→模擬get/post→檢查資料庫有更新無
前端：mock ajax→button/select模擬→檢查ajax的參數

前端嘛會當用apiary這種網站鬥相共

**Comment by leo424y** [comment]
https://github.com/twgo/twgo-exp/pull/44

**Comment by leo424y** [comment]
已加測執行新實驗 capybara  有強大整合測試功能，好有趣！
