### ISSUE TITLE
註記攏無去矣 @@

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#43]

**Comment by leo424y** [comment]
想說一開始2個人在用，先藏起來，是時候的話就搬出來，就幫大家開帳號用要先login

**Comment by sih4sing5hong5** [comment]
我標題拍毋著 = =++

**Comment by leo424y** [comment]
XD 想說之前你說不用帳號管理
dockerfile的註記嗎？ 如果是昨天發生的，那是測試生出來的dockerfile，怪怪，已mock掉

**Comment by leo424y** [comment]
啊，註記不見！被蓋掉了，很抱歉，我追一下問題。

**Comment by leo424y** [comment]
查了似乎不是被蓋掉...我再追...很抱歉

**Comment by leo424y** [comment]
仔細看了一下，註記們還在...XDDD 嚇死我

**Comment by leo424y** [comment]
嗯，開會時來討論狀況

**Comment by sih4sing5hong5** [comment]
我目睭花花看毋著
