### ISSUE TITLE
ci server的terminal數號

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#46]
呂老師佮高老師講in有可能需要ssh入去docker

咱就開一个公用的linux sh數號予in？

**Comment by leo424y** [comment]
這樣做最直接，
但聽起來比較像是請我們撈有參考意義的資料出來？ 

ex. head結果，print 正解(可能也只印部分)

請你評估哪個比較好

#45 
> 若有要撈的資料有固定的位置，直接從exp ssh ci 進 docker 撈應可行，看隊長要撈什麼，有scrpit 最棒！

**Comment by leo424y** [comment]
已開可用docker帳號，付在實驗通知信的資訊裡
