### ISSUE TITLE
音檔zip放連結

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#47]
#45 
王老師想欲聽音檔

試驗的語料袂改
所以予in靜態的zip應該較方便？

**Comment by leo424y** [comment]
量大的話zip
能夠api化的話，應該也是可以直接給 ssh reach 連結，就不會多佔空間 
#48

**Comment by leo424y** [comment]
想一下，似乎zip乾脆，再請指出要zip的路徑，我再另存

**Comment by sih4sing5hong5** [comment]
辨識語料ê`pian7sik4_gi2liau7/TW01TestAll/TW01M_TEST.tar.gz`

**Comment by leo424y** [comment]
#49  解囉，原來cat還能copy gz 帥！
另昨天聽到的less原來是for human的，已記住！謝謝隊長
http://linux.vbird.org/linux_basic/0220filemanager.php#less

**Comment by leo424y** [comment]
#49
