### ISSUE TITLE
push大量branch

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#51]
我拄才改

1. tw01+tw02 ： https://jenkins.iis.sinica.edu.tw/job/siann1-hak8_boo5-hing5/62/
2. tw01
3. twisas+tw01+tw02
4. tw01+tw02_perturb

##### 問題
- 2, 3, 4 為啥物佇jenkins內底無顯示queue？
- 4當時會出現佇exp？

**Comment by leo424y** [comment]
> 2, 3, 4 為啥物佇jenkins內底無顯示queue？

剛追了一下，看來是有在跑，只是反應稍慢，一次只會queue下一個。目前跑到2. tw01 https://jenkins.iis.sinica.edu.tw/job/siann1-hak8_boo5-hing5/63/ 

> 4當時會出現佇exp？
ci跑完就會進exp

**Comment by leo424y** [comment]
這裡可以查 GitHubPollLog 確認hook有沒有運作
https://jenkins.iis.sinica.edu.tw/job/siann1-hak8_boo5-hing5/GitHubPollLog/

**Comment by leo424y** [comment]
一次一branch
