### ISSUE TITLE
解決 docker container ssh login 問題

### ISSUE THREAD

**Issue by leo424y** [twgo/twgo-exp#52]
在docker-compose 同步ssh資訊進container即可
```
     volumes:
       - ~/.ssh:/root/.ssh		     
      - /etc/ssh:/etc/ssh
```
https://github.com/twgo/twgo-exp/commit/0de35dc3afe5a14e2aca812b5e6ded4c92bf46b1

**Comment by sih4sing5hong5** [comment]
佗一个 container？
