### ISSUE TITLE
淨化 repo

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#54]
1. new branch jenkins_原來branch#timestamp
2. exp commit
3. jenkins run
4.  kill jenkins_原來branch#timestamp

**Comment by leo424y** [comment]
因
- 目前exp tag設計以branch名為依據
- 每個commit在jenkins都會有時間
故
- 應可免timestamp
- 是否能簡化branch名？以免tag過長
- 示例：free-syllable-tw01test-仝語者 變...
- _free-syllable-tw01test-仝語者
- free-syllable-tw01test-仝語者_

 隊長覺得如何？

**Comment by sih4sing5hong5** [comment]
意思是branch名lóng kâng-khuán？

**Comment by leo424y** [comment]
是的，只是加個底線區分原始的，jenkins 與 exp 都會記錄該commit時間作區隔，不必另加stamp，我想以_free-syllable-tw01test-仝語者，形式命名，在名稱前加個下底線

**Comment by sih4sing5hong5** [comment]
若是我一擺接兩个實驗，branch名毋著衝突？

**Comment by leo424y** [comment]
一接完即下commit，馬上就砍掉，不會有衝突問題，同名是讓exp好整理同branch接的實驗在同一個tab下，這是目前的設計。

**Comment by leo424y** [comment]
fixed https://github.com/twgo/twgo-exp/commit/45e0916914b0dcb8f960d2c630ec6b4d5fd875ac
