### ISSUE TITLE
需要openstack 400G的硬碟

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#62]
敢有佗一个vm會當讓出來？
![2018-06-06 11-47-16](https://user-images.githubusercontent.com/5996555/41015992-63cf9c76-697f-11e8-8b79-dc3831eee289.png)

**Comment by leo424y** [comment]
youtube download 暫無用到
dl 1T 已釋出

**Comment by sih4sing5hong5** [comment]
資料庫敢有備份@@ ？

**Comment by leo424y** [comment]
因為只key兩個youtube頻道，未來只需要重key即可。
