### ISSUE TITLE
用nginx做proxy

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#7]
因為iiscloud的資源不足，openstack無法度設定public IP

所以資訊室建議咱佇openstack開vm

用iiscloud對外設定

進前阮有申請一台iiscloud

需要設定jenkins佮exp的proxy

設定囥佇 /etc/nginx/sites-enabled/

ip: 140.109.18.119

**Comment by leo424y** [comment]
已設定完成，依申請之domain可連
