### ISSUE TITLE
dockerhub.iis.sinica.edu.tw  申請

### ISSUE THREAD

**Issue by leo424y** [twgo/twgo-exp#72]
要申請domain一要有實體ip 
這個ci 上的dockerhub 是openstack上虛擬ip 該如何申請呢？
10.32.0.120:5000

另 jenkins-gpu.iis.sinica.edu.tw  已用gpu server ip 申請中

**Comment by leo424y** [comment]
直覺告訴我是不是用我們那台DNS server 的 ip 申請 ?

**Comment by sih4sing5hong5** [comment]
著 proxy server `140.109.18.119`
