### ISSUE TITLE
jenkins-gpu.iis.sinica.edu.tw 申請

### ISSUE THREAD

**Issue by leo424y** [twgo/twgo-exp#73]
申請 domain name 

jenkins-gpu.iis.sinica.edu.tw 
用途：實驗用GPU主機 

我給

位址：140.109.22.138 

Jeff說 ：請申請固定ip

所以不是直接給gpu主機的ip?

有勞隊長抽空回覆了，感謝你

**Comment by sih4sing5hong5** [comment]
可能當初時毋是固定ip，我才閣看覓

**Comment by leo424y** [comment]
dockerhub.iis.sinica.edu.tw 申請過了，我再進行設定
jenkins-gpu.iis.sinica.edu.tw 的固定ip再請隊長確認以利申請

**Comment by sih4sing5hong5** [comment]
> jenkins-gpu.iis.sinica.edu.tw 的固定ip再請隊長確認以利申請
domain name kah ip我做伙申請--ah

**Comment by leo424y** [comment]
OK dockerhub 可用囉！
例
FROM dockerhub.iis.sinica.edu.tw/siann1-hak8_boo5-hing5:96
 ....
