### ISSUE TITLE
幫我加入 docker hub 群組

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#81]
我數號是 sih4sing5hong5

用 Docker 開 Docker hub 權限 XD 酷！我研究一下
REF
https://docs.docker.com/registry/deploying/#native-basic-auth

**Comment by leo424y** [comment]
發現用 Docker 開 Docker hub 權限 XD 酷！
https://docs.docker.com/registry/deploying/#native-basic-auth

研究一下發現使用後要pull要先登入，可能會倒致前面的做的語言實驗可能都要加權限控管
```
Try to pull an image from the registry, or push an image to the registry. These commands fail.
Log in to the registry.
$ docker login myregistrydomain.com:5000
Provide the username and password from the first step.
Test that you can now pull an image from the registry or push an image to the registry.
```
建議若你pull主機若有固定ip，我直接allow那個ip，可能較能統一處理 XDD (省事

沒有固定ip可能就還是要這樣做了

**Comment by leo424y** [comment]
突然發現隊長在說的是官方docker XDDD 已開一個twgo(  twgogo誤開請略過) team 並加你進入，請查看 hub.docker.com

**Comment by sih4sing5hong5** [comment]
收著嘍～

**Comment by sih4sing5hong5** [comment]
- twgogo幫我提掉～～

**Comment by sih4sing5hong5** [comment]
拄才提掉--ah，是你用的抑是我離開成功XD
