### ISSUE TITLE
CI的硬碟欲用了--ah

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#87]
![2018-08-28 10-42-12](https://user-images.githubusercontent.com/5996555/44697607-1568f980-aaaf-11e8-866f-5127daea489d.png)

**Comment by leo424y** [comment]
抱歉，有點晚處理了已加500G到CI

ci@ci:~$ df -h
Filesystem                   Size  Used Avail Use% Mounted on
udev                          32G     0   32G   0% /dev
tmpfs                        6.3G   67M  6.3G   2% /run
/dev/mapper/ubuntu--vg-root  1.5T  944G  481G  67% /
tmpfs                         32G     0   32G   0% /dev/shm
tmpfs                        5.0M     0  5.0M   0% /run/lock
tmpfs                         32G     0   32G   0% /sys/fs/cgroup
tmpfs                        6.3G     0  6.3G   0% /run/user/1001

**Comment by sih4sing5hong5** [comment]
感謝
