### ISSUE TITLE
無法度接實驗

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#88]
![2018-08-28 17-53-53](https://user-images.githubusercontent.com/5996555/44715854-626ac100-aaeb-11e8-8bda-12ab24c3d8ad.png)
![2018-08-28 17-53-41](https://user-images.githubusercontent.com/5996555/44715860-64cd1b00-aaeb-11e8-955b-fb35994250ea.png)

**Comment by sih4sing5hong5** [comment]
我拄才人工共`_valid_test..`的branch thai掉

**Comment by sih4sing5hong5** [comment]
可能愛查原因，為啥物會無thai掉

**Comment by leo424y** [comment]
推測是硬碟滿造成意外中斷的例外，詳情我再查。目前要再多試試下週要交出去的，(抖
