### ISSUE TITLE
標頭分支/上游分支 改號做 train/ test

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#89]
![2018-08-28 13-43-36](https://user-images.githubusercontent.com/5996555/44715873-70b8dd00-aaeb-11e8-8cd3-f9e19004a131.png)
![2018-08-28 13-43-10](https://user-images.githubusercontent.com/5996555/44715874-70b8dd00-aaeb-11e8-9c95-0b418e58ce3e.png)

**Comment by leo424y** [comment]
已照 8/30 開會討論修改
