### ISSUE TITLE
無顯示上游分支

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#90]
![2018-08-29 09-52-37](https://user-images.githubusercontent.com/5996555/44760429-4f9acf80-ab71-11e8-94f5-e69dd41ae074.png)

**Comment by leo424y** [comment]
抱歉我設計不週，由於測試段主要是由接實驗來，我設計上游分支是在接實驗的時候一併寫進這個欄位的，已加註記在88。謝謝告知
