### ISSUE TITLE
網站看袂著實驗集

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#91]
https://exp.iis.sinica.edu.tw/

**Comment by leo424y** [comment]
回來了！ OpenStack 全部重開機的關係
我們的jenkins  image是這個沒有設定到restart得手動

docker run twgoci_jenkins_1

五個月大了呢，感謝隊長大大給機會開發

**Comment by leo424y** [comment]
補下指令
 `docker update --restart=always  twgoci_jenkins_1`
應該會自動restart了，等下次openstack又掛掉的時候看看 XD

https://github.com/moby/moby/issues/13743
