### ISSUE TITLE
訓練無自動走

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#95]
9/18 push 4个branch，jenkins攏無振動
![2018-09-19 10-29-01](https://user-images.githubusercontent.com/5996555/45727569-e13cb080-bbf6-11e8-9053-b6c6de71c58d.png)
![2018-09-19 10-29-35](https://user-images.githubusercontent.com/5996555/45727578-eac61880-bbf6-11e8-897f-6e372a7a2aa2.png)

**Comment by leo424y** [comment]
jenkins對多branch好像沒法處理，正在看多重分支的外掛，目前有線索，將試試。
未跑的已先按手動執行，稍晚會確認有沒有漏。
