### ISSUE TITLE
最近khang-khue

### ISSUE THREAD

**Issue by sih4sing5hong5** [twgo/twgo-exp#97]
A-siong:
你最近有按算安排啥物khang-khue？
我這爿有一寡語料處理想欲麻煩你～
kah處理trs檔有關係

**Comment by sih4sing5hong5** [comment]
咱約明仔載10點講好--ah
你先共khang-khue做到一个kham-tsam

**Comment by leo424y** [comment]
沒問題，明天10點skype講
